jinspins_reviews/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("movie_reviews/", include("movie_reviews.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("",
        RedirectView.as_view(url=reverse_lazy("movies_list")), name = "home",
    )
]

movie_reviews/urls.py
from django.urls import path
from movie_reviews.views import(
    new_watchlist_item,
    MoviesListView,
    # MovieReviewCreateView, 
    create_movie_review, 
    movie_review_detail, 
    update_review, 
    MovieReviewDeleteView,
    WatchlistListView,
    delete_watchlist_item,
    mark_movie_as_watched,
)

urlpatterns = [
    path("", MoviesListView.as_view(), name="movies_list"),
    # path("new_movie_review/", MovieReviewCreateView.as_view(), name="new_movie_review"),
    path("new_movie_review2/", create_movie_review, name="new_movie_review2"),
    path("full_review/<int:pk>/", movie_review_detail, name="movie_review_details"),
    path("update/<int:pk>/", update_review, name="edit_movie_review"),
    path("delete/<int:pk>", MovieReviewDeleteView.as_view(), name="delete_movie_review"),
    path("watchlist/", WatchlistListView.as_view(), name="watchlist"),
    path("watchlist/deleteitem/", delete_watchlist_item, name="delete_watchlist_item"),
    path("watchlist/new/", new_watchlist_item, name="new_watchlist_item"),
    path("watchlist/watched/", mark_movie_as_watched, name="watchlist_item_watched_urlpath"),
]
    

movie_reviews/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.

class MovieReview(models.Model):
    reviewer = models.ForeignKey(USER_MODEL, related_name="reviews", on_delete=models.CASCADE, null=True)
    reviewed_on = models.DateField(auto_now_add=True, null=True)
    title = models.CharField(max_length=60)
    poster = models.URLField(null=True, blank=True)
    release_year = models.IntegerField(
        default=2022,
        validators=[
            MaxValueValidator(2025),
            MinValueValidator(1900)
        ],
    )
    director = models.CharField(max_length=60)
    overview = models.TextField(max_length=400)
    review = models.TextField()
    rating = models.IntegerField(
        default=5,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1),
        ]
    )

    def __str__(self):
        return str(self.title) + " reviewed by " + str(self.reviewer)


class WatchlistItem(models.Model):
    owner = models.ForeignKey(USER_MODEL, related_name="watchlist_item", on_delete=models.CASCADE)
    movie = models.ForeignKey("MovieReview", related_name="watchlist_entry", on_delete=models.CASCADE)
    watch_status = models.BooleanField(verbose_name="Watched", default=False, blank=False)

    def __str__(self):
        return str(self.owner) + " wants to watch " + str(self.movie)

movie_reviews/forms.py
from django import forms

try:
    from movie_reviews.models import MovieReview

    class MovieForm(forms.ModelForm):
        class Meta:
            model = MovieReview
            fields = [
                "title",
                "poster",
                "release_year",
                "director",
                "rating",
                "overview",
                "review",
            ]

except Exception:
    pass

movie_reviews/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from movie_reviews.models import MovieReview, WatchlistItem
from django.contrib.auth.mixins import LoginRequiredMixin
from movie_reviews.forms import MovieForm
from django.shortcuts import redirect
from django.views.decorators.http import require_http_methods
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)


# Create your views here.

class MoviesListView(ListView):
    model = MovieReview
    # context_object_name = "movies_list"
    template_name = "movie_reviews/list.html"
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get("q")
        if not query:
            query = ""
        return MovieReview.objects.filter(title__icontains=query)


# class MovieReviewCreateView(LoginRequiredMixin, CreateView):
#     model = MovieReview
#     template_name = "movie_reviews/new.html"
#     fields = ["title", "poster", "release_year", "director", "overview", "review", "rating"]
#     success_url = reverse_lazy('movies_list')

#     # def get_context_data(self, **kwargs):
#     #     context = super().get_context_data(**kwargs)
#     #     user = self.request.user
#     #     context["reviewer"] = user

#     def form_valid(self, form):
#         form.instance.reviewer = self.request.user
#         return super().form_valid(form)


def create_movie_review(request):
    if request.method == "POST" and MovieForm and request.user.is_authenticated:
        form = MovieForm(request.POST)
        # form["reviewer"] = request.user
        if form.is_valid():
            form.instance.reviewer=request.user
            form.save()
            return redirect("movies_list")
    elif MovieForm:
        form = MovieForm()
    else:
        form = None
    context = {
        "form": form,
    }
    return render(request, "movie_reviews/new2.html", context)


def movie_review_detail(request, pk):
    reviewed_movie = MovieReview.objects.get(pk=pk)
    try:
        on_watchlist = request.user.watchlist_item.get(movie=reviewed_movie)
    except:
        on_watchlist = None
    context = {
        "movie": reviewed_movie if MovieReview else None,
        "watchlist_item_id": on_watchlist,
    }
    # movies_on_watchlist = []
    # for movie in request.user.watchlist_item.all():
    #     movies_on_watchlist.append(movie.movie)
    # context["movies_on_watchlist"] = movies_on_watchlist

    return render(request, "movie_reviews/details.html", context)


def update_review(request, pk):
    if MovieReview and MovieForm:
        instance = MovieReview.objects.get(pk=pk)
        if request.method == "POST":
            form = MovieForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
                return redirect('movie_review_details', pk=pk)
        else:
            form = MovieForm(instance=instance)
    else:
        form = None
    context = {
        'form': form
    }
    return render(request, 'movie_reviews/edit.html', context)


# def movie_delete_view(request, id):
#     # dictionary for initial data with
#     # field names as keys
#     context ={}
 
#     # fetch the object related to passed id
#     obj = get_object_or_404(MovieReview, id = id)
 
 
#     if request.method =="POST":
#         # delete object
#         obj.delete()
#         # after deleting redirect to
#         # home page
#         return HttpResponseRedirect("movies_list")
 
#     return render(request, "movie_reviews/delete.html", context)


class MovieReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = MovieReview
    context_object_name = "movie"
    template_name = "movie_reviews/delete.html"
    success_url = reverse_lazy("movies_list")


@require_http_methods(["POST"])
def new_watchlist_item(request):
    movie_id = request.POST.get("movie_id")
    movie = MovieReview.objects.get(id=movie_id)
    user = request.user
    try:
        WatchlistItem.objects.create(
            owner = user,
            movie = movie
        )
    except IntegrityError:
        pass
    return redirect("movie_review_details", pk=movie.id)


class WatchlistListView(ListView):
    model = WatchlistItem
    template_name = "watchlist/list.html"
    paginate_by = 40

    def get_queryset(self):
        return WatchlistItem.objects.filter(owner=self.request.user)


@require_http_methods(["POST"])
def delete_watchlist_item(request):
    watchlist_item_id = request.POST.get("watchlist_item_id")
    WatchlistItem.objects.filter(id=watchlist_item_id).delete()
    return redirect(
        "watchlist"
    )


@require_http_methods(["POST"])
def mark_movie_as_watched(request):
    watchlist_item_id = request.POST.get("watchlist_item_watched")
    WatchlistItem.objects.filter(id=watchlist_item_id).update(watch_status=True)
    return redirect(
        "watchlist"
    )
    pass

movie_reviews/templates/base.html
{% load static %}
{% load markdownify %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css">
            
        <title>Jinspins Reviews</title>
    </head>

    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </li>
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'movies_list' %}">Movie Reviews</a>
                    </li>
                    {% if user.is_authenticated %}
                        {% comment %} <li>
                            <a href="{% url 'new_movie_review' %}">Create Movie Review</a>
                        </li> {% endcomment %}
                        <li>
                            <a href="{% url 'new_movie_review2' %}">Create Movie Review</a>
                        </li>
                        <li>
                            <a href="{% url 'watchlist' %}">Watchlist ({{ user.watchlist_item.all |length }})</a>
                        </li>
                        <li>
                            {% block search_box %}
                            {% endblock search_box %}
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>

    <footer>
        {% block pagination %}
        {% endblock pagination %}
    </footer>
</html>

movie_reviews/templates/movie_reviews/delete.html
{% extends "base.html" %}

{% block content %}
    <main>
        <h2>Are you sure you want to delete this review?</h2>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes" />
            <a href="{% url 'movie_review_details' pk=movie.pk %}">Cancel </a>
        </form>
    </main>
{% endblock content %}

movie_reviews/templates/movie_reviews/details.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <a href="{% url 'edit_movie_review' movie.pk %}">Edit</a>
            <a href="{% url 'delete_movie_review' movie.pk %}">Delete</a>
        </div>
        <h1> {{ movie.title }} ({{ movie.release_year}}) reviewed by {{ movie.reviewer }}</h1>
        <img src="{{ movie.poster }}">
        <p>Directed by {{ movie.director }}</p>
        <div>
            {% if movie == watchlist_item_id.movie %}
                <p>This movie is on your watchlist</p>
                <form method="POST" action="{% url "delete_watchlist_item" %}">
                    {% csrf_token %}
                    <input type="hidden" name="watchlist_item_id" value="{{watchlist_item_id.id}}">
                    <button>Remove from Watchlist</button>
                </form>
            {% else %}
                <form method="POST" action="{% url "new_watchlist_item" %}">
                    {% csrf_token %}
                    <input type="hidden" name="movie_id" value="{{movie.id}}">
                    <button>+ Watchlist</button>
                </form>
            {% endif %}
        </div>
        <div>
            <p>Rating: {{ movie.rating }} of 10</p>
            <p>{{movie.review}}</p>
        </div>
    </main>
{% endblock content %}

movie_reviews/templates/movie_reviews/edit.html
{% extends "base.html" %}

{% block content %}
    <main>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update Review</button>
        </form>
    </main>
{% endblock content %}

movie_reviews/templates/movie_reviews/list.html
{% extends "search.html" %}


{% block content %}
    <main>
        <div class="page-title">
            <h1> Movie Reviews </h1>
        </div>
        <div class="movie-listview">
            {% for movie in moviereview_list %}
                <a href="{% url 'movie_review_details' movie.pk %}">
                <div class="movie-card">
                    <p class="movie-title">{{movie.title}}</p>
                    {% if movie.poster %}
                        <div style="movie-poster">
                            <img src="{{ movie.poster }}">
                        </div>
                    <p>Reviewed on: {{ movie.reviewed_on }}</p>
                    <p>{{ movie.overview }}</p>
                {% endif %}
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock content %}

movie_reviews/templates/movie_reviews/new.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="new-review-form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Review</button>
            </form>
        </div>
    </main>
{% endblock content %}

movie_reviews/templates/movie_reviews/new2.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="new-review-form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Review</button>
            </form>
        </div>
    </main>
{% endblock content %}

movie_reviews/templates/paginate.html
{% extends 'base.html' %}

{% block pagination %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endblock pagination %}

movie_reviews/templates/search.html
{% extends "paginate.html" %}

{% block search_box %}
    <form method="GET">
        <input type="text" name="q" style="display: inline;">
        <button type="submit">Search</button>
    </form>
{% endblock search_box%}

movie_reviews/templates/watchlist/list.html
{% extends "paginate.html" %}

{% block content %}
    <main>
        <h1 class="page-title"> Your Watchlist </h1>
        {% for movie in watchlistitem_list %}
            <div class="watchlist-grid">
                <div>
                    <img class= "watchlist-poster" src="{{ movie.movie.poster }}">
                </div>
                {% if movie.watch_status is False %}
                    <div class="watchlist-title">
                        <a href="{% url 'movie_review_details' movie.movie.id %}"> {{ movie.movie.title }} </a>
                    </div>
                    <div class="mark-as-watched-button">
                        <form method="POST" action="{% url "watchlist_item_watched_urlpath" %}">
                            {% csrf_token %}
                            <input type="hidden" name="watchlist_item_watched" value="{{movie.id}}">
                            <button>Mark as watched</button>
                        </form>
                    </div>
                    <div class="remove-from-watchlist-button">
                        <form method="POST" action="{% url "delete_watchlist_item" %}">
                            {% csrf_token %}
                            <input type="hidden" name="watchlist_item_id" value="{{movie.id}}">
                            <button>Remove from watchlist</button>
                        </form>
                    </div>
                {% else %}
                    <div class="watchlist-title">
                        <a href="{% url 'movie_review_details' movie.movie.id %}"> {{ movie.movie.title }}</a>
                    </div>
                    <div class="mark-as-watched-text">
                        Watched
                    </div>
                    <div class="remove-from-watchlist-button">
                        <form method="POST" action="{% url "delete_watchlist_item" %}">
                            {% csrf_token %}
                            <input type="hidden" name="watchlist_item_id" value="{{movie.id}}">
                            <button>Remove from watchlist</button>
                        </form>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </main>
{% endblock content %}